name: Build and Test Code

on: 
  push:
    branches-ignore:
    - '!main'
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Pulling repo
      uses: actions/checkout@v2
    - name: Installing Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Updating pip
      run: python -m pip install --upgrade pip
    - name: Installing requirements
      run: pip install -r requirements.txt
    - name: Running pytest
      run: |
        pip install pytest
        pytest

